#!/bin/sh
# Find symbols that are exported from the main library
# FIXME: Make this portable; currently works only with GNU tools nm & rev

PACKAGE=$1

if [ ! -f main.c ]; then
    echo Run this script in src!
    exit 1
fi

make >&2

(
    # Find exported symbols
    nm --defined-only .libs/*.o | cut -d " " -f 2-3 | grep ^[A-Zuvw] | cut -d " " -f 2 | sed -e "s/^${PACKAGE}_//"

    # Get internal headers that correspond to public headers
    HEADERS=`grep "^internal_HDRS = " Makefile.am | cut -d " " -f 3-`

    # Find typedefs
    grep "^typedef" $HEADERS | rev | cut -d ";" -f 2 | cut -d " " -f 1 | rev
) | sort -u # Sort for ease of diffing/debugging
