#!/bin/sh
# Find #defines that are exported from the main library

srcdir=$1

# Get internal headers that correspond to public headers
HEADERS=`grep "^internal_HDRS = " Makefile | cut -d " " -f 3-`

# Find #defined symbols
grep "^#define" $srcdir/$HEADERS | cut -d " " -f 2 | cut -d "(" -f 1
