#!/bin/sh
# Rename the project
# Requires https://github.com/rrthomas/rpl

old=`grep "^#define PACKAGE " config.h | cut -d '"' -f 2`

if [ $# -ne 1 ]; then
    echo Usage: rename-project NEW-NAME
    exit 1
fi
new=$1
shift

git mv $old.magic $new.magic
git mv src/${old}i.in src/${new}i.in
git mv src/${old}i.1.in src/${new}i.1.in
git mv doc/${old}.tex.in doc/${new}.tex.in
git mv doc/c${old}.tex.in doc/c${new}.tex.in
git mv doc/${old}.pdf doc/${new}.pdf
git mv doc/c${old}.pdf doc/c${new}.pdf
rpl --ignore-case $old $new appveyor.yml bootstrap.conf configure.ac README.md src/Makefile.am $new.magic .gitignore doc/.gitignore src/.gitignore
echo "Reset version number in configure.ac"
echo "Fix up test object files"
