CR .( Assembler words )

12 PRIMITIVES DUP DROP SWAP OVER ROT -ROT TUCK NIP PICK ROLL ?DUP >R
12 PRIMITIVES R> R@ < > = <> 0< 0> 0= 0<> U< U>
12 PRIMITIVES 0 1 -1 CELL -CELL + - >-< 1+ 1- CELL+ CELL-
12 PRIMITIVES * / MOD /MOD U/MOD S/REM 2/ CELLS ABS NEGATE MAX MIN
12 PRIMITIVES INVERT AND OR XOR LSHIFT RSHIFT 1LSHIFT 1RSHIFT @ ! C@ C!
12 PRIMITIVES +! SP@ SP! RP@ RP! EXIT UNLOOP J THROW HALT LIB LINK

CODE TRUE   B-1 BEXIT END-CODE  1 INLINE
CODE FALSE   B0 BEXIT END-CODE  1 INLINE
CODE 2*   B1LSHIFT BEXIT END-CODE  1 INLINE
CODE CELL/   B2/ B2/ BEXIT END-CODE  2 INLINE
CODE BYE   B1 BHALT END-CODE  2 INLINE
