.TH BEETLE-DUMP "1" "July 2018" "Beetle" "User Commands"
.SH NAME
beetle-dump \- Dump Beetle object files as hex and disassembly
.SH SYNOPSIS
.B beetle-dump
OBJECT\-FILE
.SH DESCRIPTION
Dump the given file, typically \fIfoo.obj\fR, as hex (\fIfoo.hex\fR) and disassembly (\fIfoo.asm\fR).
.SH "SEE ALSO"
.BR beetle (1)
.SH "REPORTING BUGS"
Report bugs to rrt@sc3d.org.
.PP
\(co Reuben Thomas 1995\-2018
.br
Beetle comes with ABSOLUTELY NO WARRANTY.
.br
You may redistribute copies of Beetle
under the terms of the GNU General Public License.
.br
For more information about these matters, see the file named COPYING.
