#!/bin/sh
# Dump Beetle object file as hex and disassembly
# (c) Reuben Thomas 2018
#
# The package is distributed under the GNU General Public License version 3,
# or, at your option, any later version.
#
# THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
# RISK.

if [ $# -ne 1 ]; then
    echo Usage: beetle-dump OBJECT-FILE
    exit 1
fi

file=$1
base=${file%.*}

# Check whether file starts with a hash-bang line
size_file=$file
head -n 1 $file > $base.tmp
if grep '^#!' $base.tmp >/dev/null; then
    tail -n +2 $file > $base.tmp
    size_file=$base.tmp
fi
size=$((`wc -c < $size_file` - 12))
rm -f $base.tmp

echo "load $file\ndump 0+$size\nquit" | beetle > $base.hex
echo "load $file\ndisassemble 0+$size\nquit" | beetle > $base.asm
