#define A beetle_A
#define ass beetle_ass
#define ass_current beetle_ass_current
#define BAD beetle_BAD
#define BYTE beetle_BYTE
#define byte_size beetle_byte_size
#define CELL beetle_CELL
#define CELL_pointer beetle_CELL_pointer
#define disass beetle_disass
#define DUCELL beetle_DUCELL
#define EP beetle_EP
#define HASHR beetle_HASHR
#define HASHS beetle_HASHS
#define I beetle_I
#define ilit beetle_ilit
#define init beetle_init
#define lit beetle_lit
#define load_byte beetle_load_byte
#define load_cell beetle_load_cell
#define load_object beetle_load_object
#define memory beetle_memory
#define MEMORY beetle_MEMORY
#define mem_realloc beetle_mem_realloc
#define NOT_ADDRESS beetle_NOT_ADDRESS
#define plit beetle_plit
#define post_dma beetle_post_dma
#define pre_dma beetle_pre_dma
#define R0 beetle_R0
#define register_args beetle_register_args
#define reverse beetle_reverse
#define reverse_cell beetle_reverse_cell
#define RP beetle_RP
#define run beetle_run
#define S0 beetle_S0
#define show_data_stack beetle_show_data_stack
#define show_return_stack beetle_show_return_stack
#define single_step beetle_single_step
#define SP beetle_SP
#define start_ass beetle_start_ass
#define store_byte beetle_store_byte
#define store_cell beetle_store_cell
#define THROW beetle_THROW
#define toass beetle_toass
#define UCELL beetle_UCELL
#define val_data_stack beetle_val_data_stack
#define CELL_W beetle_CELL_W
#define POINTER_W beetle_POINTER_W
#define STACK_UNDERFLOW beetle_STACK_UNDERFLOW
#define STACK_DIRECTION beetle_STACK_DIRECTION
#define CELL_BIT beetle_CELL_BIT
#define CHAR_MASK beetle_CHAR_MASK
#define ENDISM beetle_ENDISM
#define CELL_MAX beetle_CELL_MAX
#define ALIGN beetle_ALIGN
#define IS_ALIGNED beetle_IS_ALIGNED
#define PUSH_DOUBLE beetle_PUSH_DOUBLE
#define POP_DOUBLE beetle_POP_DOUBLE
#define PUSH_RETURN beetle_PUSH_RETURN
#define POP_RETURN beetle_POP_RETURN
#define LOAD_BYTE beetle_LOAD_BYTE
#define STORE_BYTE beetle_STORE_BYTE
#define LOAD_CELL beetle_LOAD_CELL
#define STORE_CELL beetle_STORE_CELL
#define CHECKED beetle_CHECKED
#define POP beetle_POP
#define PUSH beetle_PUSH
#define ARSHIFT beetle_ARSHIFT
